title = "JBowe Alacritty"

[cursor]
style = "Block"
unfocused_hollow = true

[font.normal]
family = "Hurmit Nerd Font"

[visual_bell]
animation = "Ease"
color = "0xffffff"
duration = 10

[window]
decorations = "full"
opacity = 0.75
