[cursor]
style = "Block"
unfocused_hollow = true

[font.normal]
family = "Hurmit Nerd Font"

[bell]
animation = "Ease"
color = "0xf0f0f0"
duration = 10

[window]
opacity = 0.7
startup_mode = "Maximized"

[mouse]
hide_when_typing = true
