# Change colorscheme to Nord
# Credit: https://github.com/nordtheme/alacritty
general.import = ["~/.config/alacritty/nord.toml"]

[cursor]
style = "Block"
vi_mode_style = "Block"
unfocused_hollow = true

[bell]
animation = "Ease"
color = "0xf0f0f0"
duration = 10

[window]
opacity = 0.7
startup_mode = "Maximized"
decorations = "none"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    {key="v", mods="Control|Alt", mode="~Search", action="ToggleViMode"},
    {key="Escape", mode="Vi", action="ToggleViMode"},
]
