theme = "boweflex_transparent"

[editor]
line-number = "relative"
mouse = false
cursorline = true
color-modes = true

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 1

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false
