theme = "boweflex_transparent"

[editor]
line-number = "relative"
mouse = false
cursorline = true
color-modes = true
rulers = [80]

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false
